'use client';
import {useState} from 'react';
import {useRouter} from 'next/navigation';
import {ArrowDown,ArrowUp,ImagePlus,Send,Star,Trash2,Video} from 'lucide-react';
import * as tus from 'tus-js-client';
import {browserClient} from '@/lib/supabase/browser';
import {supabaseEnv} from '@/lib/supabase/config';
import type {DbImage,DbProperty,DbVideo,Profile,PublicationStatus,PropertyStatus,Purpose} from '@/lib/properties/types';
export type EditorImage=DbImage&{preview:string};
export type EditorVideo=DbVideo&{preview:string};
type Form={title:string;title_en:string;slug:string;description:string;description_en:string;short_description:string;property_type:string;purpose:Purpose;neighborhood:string;city:string;bedrooms:number;suites:number;bathrooms:number;parking_spaces:number;area:string;land_area:string;features:string;property_status:PropertyStatus;featured:boolean;seo_title:string;seo_description:string;review_note:string};
function initialForm(p?:DbProperty):Form{return {title:p?.title||'',title_en:p?.title_en||'',slug:p?.slug||'',description:p?.description||'',description_en:p?.description_en||'',short_description:p?.short_description||'',property_type:p?.property_type||'Casa',purpose:p?.purpose||'sale',neighborhood:p?.neighborhood||'',city:p?.city||'Armação dos Búzios',bedrooms:p?.bedrooms||0,suites:p?.suites||0,bathrooms:p?.bathrooms||0,parking_spaces:p?.parking_spaces||0,area:p?.area?.toString()||'',land_area:p?.land_area?.toString()||'',features:p?.features?.join('\n')||'',property_status:p?.property_status||'available',featured:p?.featured||false,seo_title:p?.seo_title||'',seo_description:p?.seo_description||'',review_note:p?.review_note||''}}
function slugify(value:string){return value.normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'').slice(0,95)}
function saveErrorMessage(error:unknown){if(error instanceof Error)return error.message;if(error&&typeof error==='object'){const value=error as {message?:unknown;code?:unknown};if(value.code==='42501')return 'O Supabase recusou o salvamento por uma regra de segurança. Atualize a página e entre novamente no painel; se continuar, avise o administrador.';if(typeof value.message==='string')return value.message}return 'Não foi possível salvar. Seus dados permanecem na tela.'}
async function digest(file:File){const bytes=await file.arrayBuffer();const hash=await crypto.subtle.digest('SHA-256',bytes);return Array.from(new Uint8Array(hash)).map(b=>b.toString(16).padStart(2,'0')).join('')}
async function optimized(file:File,maxWidth:number,quality:number){const bitmap=await createImageBitmap(file);const scale=Math.min(1,maxWidth/bitmap.width);const canvas=document.createElement('canvas');canvas.width=Math.round(bitmap.width*scale);canvas.height=Math.round(bitmap.height*scale);canvas.getContext('2d')?.drawImage(bitmap,0,0,canvas.width,canvas.height);bitmap.close();return new Promise<Blob>((resolve,reject)=>canvas.toBlob(blob=>blob?resolve(blob):reject(new Error('Não foi possível otimizar a foto.')),'image/webp',quality))}
function videoType(file:File){if(['video/mp4','video/webm','video/quicktime'].includes(file.type))return file.type;const ext=file.name.split('.').pop()?.toLowerCase();return ext==='mp4'?'video/mp4':ext==='webm'?'video/webm':ext==='mov'?'video/quicktime':''}
function videoEndpoint(){const base=new URL(supabaseEnv().url);if(base.hostname.endsWith('.supabase.co'))base.hostname=base.hostname.replace('.supabase.co','.storage.supabase.co');return `${base.origin}/storage/v1/upload/resumable`}
export function PropertyEditor({profile,initial,initialImages=[],initialVideos=[]}:{profile:Profile;initial?:DbProperty;initialImages?:EditorImage[];initialVideos?:EditorVideo[]}){
 const router=useRouter();const admin=profile.role==='admin';const [form,setForm]=useState<Form>(()=>initialForm(initial));const [id,setId]=useState(initial?.id||'');const [status,setStatus]=useState<PublicationStatus>(initial?.publication_status||'draft');const [photos,setPhotos]=useState(initialImages);const [videos,setVideos]=useState(initialVideos);const [busy,setBusy]=useState(false);const [message,setMessage]=useState('');const [error,setError]=useState('');const [progress,setProgress]=useState('');
 const update=<K extends keyof Form>(key:K,value:Form[K])=>setForm(prev=>({...prev,[key]:value}));
 const db=browserClient();
 async function save(nextStatus?:PublicationStatus):Promise<string|null>{setBusy(true);setError('');setMessage('');try{
  const payload={title:form.title.trim(),title_en:form.title_en.trim(),slug:id?(admin?slugify(form.slug):form.slug):(admin&&form.slug?slugify(form.slug):`${slugify(form.title)||'imovel'}-${crypto.randomUUID().slice(0,8)}`),description:form.description.trim(),description_en:form.description_en.trim(),short_description:form.short_description.trim(),property_type:form.property_type.trim(),purpose:form.purpose,neighborhood:form.neighborhood.trim(),city:form.city.trim(),bedrooms:Number(form.bedrooms),suites:Number(form.suites),bathrooms:Number(form.bathrooms),parking_spaces:Number(form.parking_spaces),area:form.area?Number(form.area):null,land_area:form.land_area?Number(form.land_area):null,features:form.features.split('\n').map(s=>s.trim()).filter(Boolean),property_status:form.property_status,...(admin?{featured:form.featured,seo_title:form.seo_title||null,seo_description:form.seo_description||null,review_note:form.review_note||null}:{})};
  if((nextStatus==='pending_review'||nextStatus==='published')&&(payload.title.length<3||payload.city.length<2))throw Error('Para enviar ou publicar, informe um título e uma cidade.');
  if(!payload.title)throw Error('Informe o nome do imóvel para continuar.');
  let propertyId=id;
  if(id){const {error}=await db.from('properties').update({...payload,...(nextStatus?{publication_status:nextStatus}:{})}).eq('id',id);if(error)throw error}
  else {const {data:{user},error:sessionError}=await db.auth.getUser();if(sessionError)throw sessionError;if(!user)throw new Error('Sua sessão expirou. Entre novamente no painel para continuar.');if(user.id!==profile.id)throw new Error('A sessão ativa não corresponde ao perfil carregado. Atualize a página e entre novamente no painel.');propertyId=crypto.randomUUID();const {error}=await db.from('properties').insert({id:propertyId,...payload,publication_status:'draft',created_by:user.id});if(error)throw error;setId(propertyId);setForm(prev=>({...prev,slug:payload.slug}));history.replaceState(null,'',`/admin/imoveis/${payload.slug}`)}
  if(nextStatus&&nextStatus!=='draft'&&!id){const {error}=await db.from('properties').update({publication_status:nextStatus}).eq('id',propertyId);if(error)throw error}
  if(nextStatus)setStatus(nextStatus);setMessage(nextStatus==='pending_review'?'Imóvel enviado para revisão':nextStatus==='published'?'Imóvel publicado':nextStatus==='rejected'?'Imóvel rejeitado':'Rascunho salvo automaticamente');router.refresh();return propertyId;
 }catch(caught){setError(saveErrorMessage(caught));return null}finally{setBusy(false)}}
 async function setPropertyStatus(value:PropertyStatus){if(!id){update('property_status',value);return}setBusy(true);setError('');const {error}=await db.from('properties').update({property_status:value}).eq('id',id);setBusy(false);if(error){setError(error.message);return}update('property_status',value);setMessage('Situação do imóvel atualizada.');router.refresh()}
 async function upload(files:FileList|null){if(!files?.length)return;if(status==='published'){setError('Envie o imóvel para revisão antes de alterar as fotos.');return}setError('');let propertyId=id;if(!propertyId){propertyId=await save('draft')||'';if(!propertyId)return}setBusy(true);let current=[...photos];try{for(let index=0;index<files.length;index++){const file=files[index];setProgress(`Enviando foto ${index+1} de ${files.length}…`);if(!['image/jpeg','image/png','image/webp'].includes(file.type)||file.size>15*1024*1024)throw Error(`${file.name}: use JPG, PNG ou WEBP de até 15 MB.`);const sha256=await digest(file);if(current.some(p=>p.sha256===sha256))continue;const full=await optimized(file,1800,.84),thumb=await optimized(file,640,.77);const base=`${propertyId}/${crypto.randomUUID()}`;const path=`${base}.webp`,small=`${base}-thumb.webp`;const bucket=db.storage.from('property-images');const first=await bucket.upload(path,full,{contentType:'image/webp',upsert:false});if(first.error)throw first.error;const second=await bucket.upload(small,thumb,{contentType:'image/webp',upsert:false});if(second.error){await bucket.remove([path]);throw second.error}const {data,error}=await db.from('property_images').insert({property_id:propertyId,storage_path:path,thumbnail_path:small,sha256,position:current.length,is_cover:current.length===0,alt_text:`${form.title} — foto ${current.length+1}`}).select('*').single();if(error){await bucket.remove([path,small]);throw error}const {data:signed}=await bucket.createSignedUrl(small,3600);current=[...current,{...(data as DbImage),preview:signed?.signedUrl||URL.createObjectURL(thumb)}];setPhotos(current)}}catch(caught){setError(caught instanceof Error?caught.message:'Upload falhou. As fotos já enviadas foram mantidas.')}finally{setBusy(false);setProgress('');router.refresh()}}
 async function uploadVideos(files:FileList|null){if(!files?.length)return;if(status==='published'){setError('Envie o imóvel para revisão antes de alterar os vídeos.');return}setError('');let propertyId=id;if(!propertyId){propertyId=await save('draft')||'';if(!propertyId)return}setBusy(true);let current=[...videos];try{const {data:{session},error:sessionError}=await db.auth.getSession();if(sessionError||!session)throw Error('Sua sessão expirou. Entre novamente no painel.');for(let index=0;index<files.length;index++){const file=files[index];const contentType=videoType(file);if(!contentType||!file.size||file.size>50*1024*1024)throw Error(`${file.name}: use MP4, WEBM ou MOV de até 50 MB.`);setProgress(`Preparando vídeo ${index+1} de ${files.length}…`);const sha256=await digest(file);if(current.some(v=>v.sha256===sha256))continue;const extension=contentType==='video/mp4'?'mp4':contentType==='video/webm'?'webm':'mov';const path=`${propertyId}/${sha256}.${extension}`;await new Promise<void>((resolve,reject)=>{const task=new tus.Upload(file,{endpoint:videoEndpoint(),headers:{authorization:`Bearer ${session.access_token}`},metadata:{bucketName:'property-videos',objectName:path,contentType,cacheControl:'3600'},chunkSize:6*1024*1024,retryDelays:[0,3000,5000,10000,20000],uploadDataDuringCreation:true,removeFingerprintOnSuccess:true,fingerprint:async()=>`yuri-property-video-${propertyId}-${sha256}`,onProgress:(sent,total)=>setProgress(`Enviando vídeo ${index+1} de ${files.length} · ${Math.round(sent/total*100)}%`),onError:reject,onSuccess:()=>resolve()});void task.findPreviousUploads().then(previous=>{if(previous.length)task.resumeFromPreviousUpload(previous[0]);task.start()}).catch(reject)});const bucket=db.storage.from('property-videos');const {data,error}=await db.from('property_videos').insert({property_id:propertyId,storage_path:path,content_type:contentType,byte_size:file.size,sha256,position:current.length}).select('*').single();if(error){await bucket.remove([path]);throw error}const {data:signed,error:signError}=await bucket.createSignedUrl(path,86400);if(signError||!signed?.signedUrl)throw Error('Vídeo salvo, mas não foi possível abrir a prévia. Atualize a página.');current=[...current,{...(data as DbVideo),preview:signed.signedUrl}];setVideos(current)}setMessage('Vídeo enviado com sucesso.')}catch(caught){setError(caught instanceof Error?caught.message:'O upload do vídeo falhou. Os vídeos anteriores foram mantidos.')}finally{setBusy(false);setProgress('');router.refresh()}}
 async function moveVideo(video:EditorVideo,direction:number){const from=videos.findIndex(v=>v.id===video.id),to=from+direction;if(to<0||to>=videos.length)return;const copy=[...videos];[copy[from],copy[to]]=[copy[to],copy[from]];setBusy(true);for(let i=0;i<copy.length;i++){const {error}=await db.from('property_videos').update({position:i}).eq('id',copy[i].id);if(error){setError(error.message);setBusy(false);return}}setVideos(copy.map((v,i)=>({...v,position:i})));setBusy(false);setMessage('Ordem dos vídeos salva.')}
 async function removeVideo(video:EditorVideo){if(!confirm('Remover este vídeo?'))return;setBusy(true);const {error}=await db.from('property_videos').delete().eq('id',video.id);if(error){setError(error.message);setBusy(false);return}const {error:storageError}=await db.storage.from('property-videos').remove([video.storage_path]);setVideos(videos.filter(v=>v.id!==video.id));setBusy(false);setMessage(storageError?'Vídeo removido do anúncio; a limpeza do arquivo precisa de atenção.':'Vídeo removido.')}
 async function cover(image:EditorImage){if(image.is_cover)return;setBusy(true);const current=photos.find(p=>p.is_cover);if(current){const {error}=await db.from('property_images').update({is_cover:false}).eq('id',current.id);if(error){setError(error.message);setBusy(false);return}}const {error}=await db.from('property_images').update({is_cover:true}).eq('id',image.id);setBusy(false);if(error){setError(error.message);return}setPhotos(photos.map(p=>({...p,is_cover:p.id===image.id})));setMessage('Foto de capa atualizada.')}
 async function move(image:EditorImage,direction:number){const from=photos.findIndex(p=>p.id===image.id),to=from+direction;if(to<0||to>=photos.length)return;const copy=[...photos];[copy[from],copy[to]]=[copy[to],copy[from]];setBusy(true);for(let i=0;i<copy.length;i++){const {error}=await db.from('property_images').update({position:i}).eq('id',copy[i].id);if(error){setError(error.message);setBusy(false);return}}setPhotos(copy.map((p,i)=>({...p,position:i})));setBusy(false);setMessage('Ordem das fotos salva.')}
 async function remove(image:EditorImage){if(!confirm('Remover esta foto?'))return;setBusy(true);const {error}=await db.from('property_images').delete().eq('id',image.id);if(error){setError(error.message);setBusy(false);return}await db.storage.from('property-images').remove([image.storage_path,image.thumbnail_path]);setPhotos(photos.filter(p=>p.id!==image.id));setBusy(false);setMessage('Foto removida.')}
 async function permanentDelete(){if(!admin||!id)return;const answer=prompt('Para excluir permanentemente este imóvel e todas as fotos, digite EXCLUIR:');if(answer!=='EXCLUIR')return;setBusy(true);setError('');try{const response=await fetch(`/api/admin/properties/${id}`,{method:'DELETE'});const body=await response.json() as {error?:string;warning?:string};if(!response.ok)throw Error(body.error||'Exclusão falhou');if(body.warning)alert(body.warning);router.push('/admin/imoveis');router.refresh()}catch(caught){setError(caught instanceof Error?caught.message:'Exclusão falhou')}finally{setBusy(false)}}
 return <div className="admin-form">
  <p className="admin-note">Status: {status==='pending_review'?'Aguardando revisão':status==='published'?'Publicado':status==='rejected'?'Rejeitado':'Rascunho'}{admin&&initial?.review_note&&<span> · Observação: {initial.review_note}</span>}</p>
  <fieldset><legend>Informações básicas</legend><label>Nome do imóvel<input value={form.title} onChange={e=>update('title',e.target.value)} required/></label><div className="admin-two"><label>Tipo<input value={form.property_type} onChange={e=>update('property_type',e.target.value)} placeholder="Casa, apartamento, terreno…"/></label><label>Finalidade<select value={form.purpose} onChange={e=>update('purpose',e.target.value as Purpose)}><option value="sale">Venda</option><option value="rent">Aluguel</option><option value="holiday">Temporada</option></select></label></div><div className="admin-two"><label>Bairro<input value={form.neighborhood} onChange={e=>update('neighborhood',e.target.value)}/></label><label>Cidade<input value={form.city} onChange={e=>update('city',e.target.value)}/></label></div><label>Situação<select value={form.property_status} onChange={e=>setPropertyStatus(e.target.value as PropertyStatus)}><option value="available">Disponível</option><option value="inactive">Inativo</option><option value="sold">Vendido</option><option value="rented">Alugado</option></select></label></fieldset>
  <fieldset><legend>Características</legend><div className="admin-four">{([['bedrooms','Quartos'],['suites','Suítes'],['bathrooms','Banheiros'],['parking_spaces','Vagas']] as const).map(([key,label])=><label key={key}>{label}<input type="number" min="0" value={form[key]} onChange={e=>update(key,Number(e.target.value))}/></label>)}</div><div className="admin-two"><label>Área construída (m²)<input type="number" min="0" step="0.01" value={form.area} onChange={e=>update('area',e.target.value)}/></label><label>Terreno (m²)<input type="number" min="0" step="0.01" value={form.land_area} onChange={e=>update('land_area',e.target.value)}/></label></div><label>Diferenciais (um por linha)<textarea value={form.features} onChange={e=>update('features',e.target.value)}/></label></fieldset>
  <fieldset><legend>Descrição</legend><label>Resumo<input value={form.short_description} onChange={e=>update('short_description',e.target.value)}/></label><label>Descrição completa<textarea value={form.description} onChange={e=>update('description',e.target.value)}/></label><label>Título em inglês (opcional)<input value={form.title_en} onChange={e=>update('title_en',e.target.value)}/></label><label>Descrição em inglês (opcional)<textarea value={form.description_en} onChange={e=>update('description_en',e.target.value)}/></label></fieldset>
  {admin&&<fieldset><legend>Revisão e SEO</legend><label><input type="checkbox" checked={form.featured} onChange={e=>update('featured',e.target.checked)}/> Destaque na Home</label><label>Título SEO<input value={form.seo_title} onChange={e=>update('seo_title',e.target.value)}/></label><label>Descrição SEO<textarea value={form.seo_description} onChange={e=>update('seo_description',e.target.value)}/></label><label>Observação da revisão<textarea value={form.review_note} onChange={e=>update('review_note',e.target.value)}/></label>{id&&status==='pending_review'&&<div className="admin-actions"><button type="button" disabled={busy} onClick={()=>save('published')}>Aprovar e publicar</button><button type="button" className="admin-secondary" disabled={busy||!form.review_note.trim()} onClick={()=>save('rejected')}>Rejeitar com observação</button></div>}{id&&<button type="button" className="admin-secondary" disabled={busy} onClick={permanentDelete}><Trash2 size={16} aria-hidden="true"/> Excluir permanentemente</button>}</fieldset>}
  <fieldset><legend><ImagePlus size={17} aria-hidden="true"/> Fotos</legend><p className="admin-note">Opcional por enquanto. JPG, PNG ou WEBP até 15 MB. As imagens são otimizadas automaticamente; ao selecionar a primeira foto, o rascunho é criado automaticamente. Se adicionar fotos, você pode escolher uma como capa.</p><input type="file" accept="image/jpeg,image/png,image/webp" multiple disabled={busy||status==='published'} onChange={e=>{void upload(e.target.files);e.target.value=''}}/>{progress.includes('foto')&&<p role="status">{progress}</p>}<div className="admin-photos">{photos.map((photo,index)=><div className="admin-photo" key={photo.id}>{photo.preview&&<img src={photo.preview} alt={photo.alt_text||`Foto ${index+1}`}/>}<small>{photo.is_cover?'Foto de capa':`Foto ${index+1}`}</small><button type="button" aria-label={`Mover foto ${index+1} para cima`} title="Mover para cima" disabled={busy||status==='published'||index===0} onClick={()=>move(photo,-1)}><ArrowUp size={15} aria-hidden="true"/></button><button type="button" aria-label={`Mover foto ${index+1} para baixo`} title="Mover para baixo" disabled={busy||status==='published'||index===photos.length-1} onClick={()=>move(photo,1)}><ArrowDown size={15} aria-hidden="true"/></button><button type="button" aria-label="Definir como foto de capa" title="Definir como capa" disabled={busy||status==='published'||photo.is_cover} onClick={()=>cover(photo)}><Star size={15} aria-hidden="true"/> Capa</button><button type="button" aria-label="Remover foto" title="Remover foto" disabled={busy||status==='published'} onClick={()=>remove(photo)}><Trash2 size={15} aria-hidden="true"/> Remover</button></div>)}</div></fieldset>
  <fieldset><legend><Video size={17} aria-hidden="true"/> Vídeos</legend><p className="admin-note">MP4, WEBM ou MOV até 50 MB por vídeo. MP4 oferece melhor compatibilidade nos navegadores. O envio pode ser retomado se a conexão cair; ao selecionar o primeiro vídeo, um rascunho é criado automaticamente.</p><input type="file" accept="video/mp4,video/webm,video/quicktime,.mp4,.webm,.mov" multiple disabled={busy||status==='published'} onChange={e=>{void uploadVideos(e.target.files);e.target.value=''}}/>{progress.includes('vídeo')&&<p role="status">{progress}</p>}<div className="admin-videos">{videos.map((video,index)=><div className="admin-video" key={video.id}><video src={video.preview} controls preload="metadata" playsInline aria-label={`Vídeo ${index+1} do imóvel`}/><small>Vídeo {index+1} · {(video.byte_size/1024/1024).toFixed(1)} MB</small><div><button type="button" aria-label={`Mover vídeo ${index+1} para cima`} title="Mover para cima" disabled={busy||status==='published'||index===0} onClick={()=>moveVideo(video,-1)}><ArrowUp size={15} aria-hidden="true"/></button><button type="button" aria-label={`Mover vídeo ${index+1} para baixo`} title="Mover para baixo" disabled={busy||status==='published'||index===videos.length-1} onClick={()=>moveVideo(video,1)}><ArrowDown size={15} aria-hidden="true"/></button><button type="button" aria-label={`Remover vídeo ${index+1}`} title="Remover vídeo" disabled={busy||status==='published'} onClick={()=>removeVideo(video)}><Trash2 size={15} aria-hidden="true"/> Remover</button></div></div>)}</div></fieldset>
  {error&&<p role="alert" className="admin-error">{error}</p>}{message&&<p role="status" className="admin-success">{message}</p>}
  <div className="admin-actions"><button type="button" disabled={busy} onClick={()=>save('pending_review')}><Send size={16} aria-hidden="true"/> {busy?'Aguarde…':'Enviar para revisão'}</button></div>
  {id&&status==='published'&&<a href={`/imoveis/${form.slug||initial?.slug}`} target="_blank" rel="noreferrer">Visualizar no site ↗</a>}
 </div>;
}
